<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>m</string>
	</array>
	<key>name</key>
	<string>Murphi</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>Functions/Procedure</string>
			<key>match</key>
			<string>\b(([F|f]unction)|([P|p]rocedure)|([B|b]egin)|([E|e]nd)|([E|e]ndfunction)|([E|e]ndprocedure)|([R|r]eturn))\b</string>
			<key>name</key>
			<string>support.function.m</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Rules</string>
			<key>match</key>
			<string>\b(([I|i]nvariant)|([R|r]ule)|([R|r]uleset)|([S|s]tartstate)|([E|e]ndrule)|([E|e]ndruleset)|([E|e]ndstartstate))\b</string>
			<key>name</key>
			<string>constant.numeric.m</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Structure</string>
			<key>match</key>
			<string>\b(([A|a]rray)|([E|e]ndrecord)|([O|o]f)|([R|r]ecord)|([U|u]nion))\b</string>
			<key>name</key>
			<string>support.type.m</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Sets and enumeration</string>
			<key>match</key>
			<string>\b(([B|b]oolean)|([M|m]ultiset)|([S|s]calarset)|([E|e]num))\b</string>
			<key>name</key>
			<string>variable.parameter.m</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Datatypes</string>
			<key>match</key>
			<string>\b(([C|c]onst)|([T|t]ype)|([V|v]ar))\b</string>
			<key>name</key>
			<string>constant.numeric.m</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Boolean</string>
			<key>match</key>
			<string>\b(([F|f]alse)|([T|t]rue))\b</string>
			<key>name</key>
			<string>keyword.control.m</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>If</string>
			<key>match</key>
			<string>\b(([I|i]f)|([T|t]hen)|([E|e]lse)|([E|e]lsif)|([E|e]ndif))\b</string>
			<key>name</key>
			<string>keyword.control.m</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Switch</string>
			<key>match</key>
			<string>\b(([E|e]ndswitch)|([S|s]witch)|([C|c]ase))\b</string>
			<key>name</key>
			<string>constant.numeric.m</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Repeat</string>
			<key>match</key>
			<string>\b(([D|d]o)|([E|e]ndexists)|([E|e]ndfor)|([E|e]ndforall)|([E|e]ndwhile))\b</string>
			<key>name</key>
			<string>keyword.operator.m</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Repeat</string>
			<key>match</key>
			<string>\b(([E|e]xists)|([F|f]or)|([F|f]orall)|([T|t]o)|([W|w]hile))\b</string>
			<key>name</key>
			<string>keyword.operator.m</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Assert Error</string>
			<key>match</key>
			<string>\b(([A|a]ssert)|([E|e]rror))\b</string>
			<key>name</key>
			<string>keyword.control.m</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Undefine Value</string>
			<key>match</key>
			<string>\b(([U|u]ndefine))\b</string>
			<key>name</key>
			<string>keyword.control.m</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Output</string>
			<key>match</key>
			<string>\b([P|p]ut)\b</string>
			<key>name</key>
			<string>string.quoted</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Keywords</string>
			<key>match</key>
			<string>\b(([A|a]lias)|([B|b]y)|([C|c]hoose )|([E|e]ndchoose)|([C|c]lear)|([E|e]ndalias)|([I|i]n )|([I|i]nterleaved)|([L|l]og )|([P|p]rocess)|([P|p]rogram)|([T|t]raceuntil))\b</string>
			<key>name</key>
			<string>keyword.other.m</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Member</string>
			<key>match</key>
			<string>\b(([I|i]smember)|([I|i]sundefined)|([M|m]ultisetadd)|([M|m]ultisetcount )|([M|m]ultisetremove)|([M|m]ultisetremovepred))\b</string>
			<key>name</key>
			<string>markup.bold.m</string>
		</dict>
		<dict>
			<key>comment</key>
			<string>Error</string>
			<key>match</key>
			<string>((\=\=[^&gt;])|\&amp;\&amp;|\|\|)</string>
			<key>name</key>
			<string>invalid.illegal.m</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(--|\/\/)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.line.m</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>comment.line.m</string>
			<key>end</key>
			<string>\n</string>
			<key>name</key>
			<string>Comment line</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\/\*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.block.m</string>
				</dict>
			</dict>
			<key>contentName</key>
			<string>comment.block.m</string>
			<key>end</key>
			<string>(\*\/)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>comment.block.m</string>
				</dict>
			</dict>
			<key>name</key>
			<string>Comment block</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.m</string>
	<key>uuid</key>
	<string>2014e228-1e33-49c7-9f69-93da82ddf436</string>
</dict>
</plist>
